"""add receipt fields

Revision ID: 2e10b2430d27
Revises: 2f1c6df28639
Create Date: 2026-06-24 14:12:33.287945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e10b2430d27'
down_revision: Union[str, Sequence[str], None] = '2f1c6df28639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('receipt_path', sa.String(length=255), nullable=True))
    op.add_column('investments', sa.Column('bank_reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'bank_reference')
    op.drop_column('investments', 'receipt_path')
    # ### end Alembic commands ###
